version: '3.9'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017
    command: npm run dev
    depends_on:
      - mongo

      
volumes:
  mongo-db: