version: '3.9'
services:
  mongo_db:
    image: mongo:latest
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db
    restart: always
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongo_db://mongo:27017/test102
    depends_on:
      - mongo

volumes:
  mongo_db: {}